version: '3.2'

services:

  mongo:
    image: mongo:latest
    container_name: mongo-nest-clean-api
    ports:
      - '27017-27019:27017-27019'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./volumes/mongo/databases:/data/db
      - ./volumes/mongo/collections:/docker-entrypoint-initdb.d
    networks:
      - mongo-nest-clean-api

networks:
  mongo-nest-clean-api:
    driver: bridge
